[project]
name = "movie-database"
version = "0.1.0"
description = "Reusable movie database utilities"
authors = [
    { name = "Samuel Todd" }
]
requires-python = ">=3.10"

dependencies = [
    "psycopg2-binary>=2.9.12,<3.0.0",
    "requests (>=2.34.2,<3.0.0)",
    "dotenv (>=0.9.9,<0.10.0)"
]

[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"